name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/moodify_tracker_service:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Deploy to AKS
        if: success() && github.ref == 'refs/heads/main'
        uses: Azure/k8s-deploy@v5
        with:
          action: 'deploy'
          manifests: |
            k8s/tracker-service-deployment.yaml
          strategy: 'basic'
          images: '${{ secrets.REGISTRY_USERNAME }}/moodify_tracker_service:latest'
          pull-images: false
          namespace: 'development'